#!/usr/bin/expect

# Get configuration settings from the switch
# usage: ./get-system-setup 192.168.1.2 admin password

# Written by Philipp Klaus

# Credits to:
# http://stackoverflow.com/a/7013379
# http://stackoverflow.com/a/10190013

set hostname [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]

if { $hostname == "" || $username == "" || $password == "" }  {
  puts "Usage: <hostname> <username> <password>\n"
  exit 1
}

set timeout 20
set stty_init "rows 10000 cols 200"
spawn -nottycopy telnet $hostname

expect "User:"
send "$username\r"
expect "Password:"
send "$password\r"

expect ">"
send "enable\r"
expect "Password:"
send "$password\r"

expect "#"
send "show system-info\r"
expect "#"
send "show running-config\r"
expect "#"
send "show system-time\r"
expect "#"
send "show user configuration\r"
expect "#"
send "show user account-list\r"
expect "#"
send "show interface configuration\r"
expect "#"
send "show interface status\r"
expect "#"
send "show interface switchport\r"
expect "#"
send "show monitor session\r"
expect "#"
send "show storm-control\r"
expect "#"
send "show ip dos-prevent\r"
expect "#"
send "show logging loghost\r"
expect "#"
send "show ip arp inspection\r"
expect "#"
send "show ip source binding\r"
expect "#"
send "show vlan\r"
expect "#"
send "show voice vlan\r"
expect "#"
send "show voice vlan switchport\r"
expect "#"
send "show qos status\r"
expect "#"
send "show dot1x global\r"
expect "#"
send "show dot1x interface\r"
expect "#"
send "show ip dhcp snooping\r"
expect "#"
send "exit\r"
expect ">"
send "exit\r"

